# Generated by Django 4.1.5 on 2023-02-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmakesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='gfftfg', upload_to='', verbose_name='pics'),
            preserve_default=False,
        ),
    ]
